# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[('1', '男'), ('0', '女')], max_length=1)),
                ('pic_url', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
