# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('0', '女')], max_length=1),
        ),
    ]
