# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_cates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('pic_url', models.CharField(max_length=200)),
                ('gnum', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('info', models.TextField(max_length=255)),
                ('ordernum', models.IntegerField(default=0)),
                ('clicknum', models.IntegerField(default=0)),
                ('adddtime', models.DateTimeField(auto_now_add=True)),
                ('cateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Cates')),
            ],
        ),
    ]
