# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('info', models.CharField(max_length=255)),
                ('isselect', models.BooleanField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('upid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='zhen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Citys'),
        ),
    ]
