# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20181126_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=255)),
                ('wl', models.CharField(max_length=50)),
                ('paytype', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Orderinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('pic_url', models.CharField(max_length=100)),
                ('ordid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Order')),
            ],
        ),
    ]
